### ISSUE TITLE
Can I copy?

### ISSUE THREAD

**Issue by moyamo** [seanwentzel/icpc-notebook#4]
Hi Sean, it's Yaseen Mowzer.

Do you mind if David, Bronson and I use this as a starting point for our ICPC notebook?

**Comment by seanwentzel** [comment]
You're welcome to, but this isn't very complete and I think there are bugs in it. I'd recommend something like https://cs.stanford.edu/group/acm/SLPC/notebook.pdf

**Comment by moyamo** [comment]
Thanks! I'll take a look.
